# Generated by Django 5.0 on 2023-12-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Назва')),
                ('number', models.IntegerField(max_length=3, verbose_name='Кількість')),
                ('date', models.DateTimeField(verbose_name='Дата')),
            ],
        ),
    ]
